version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8091:8091"
    restart: on-failure
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - BACKEND_URL=http://backend:8091
