CREATE TABLE cars
(
    id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plate_code   VARCHAR(6)                           NOT NULL,
    brand        VARCHAR(30)                          NOT NULL,
    model        VARCHAR(30)                          NOT NULL,
    subsidiary   VARCHAR(30)                          NOT NULL,
    color        VARCHAR(10)                          NOT NULL,
    factory_year INT                                  NOT NULL,
    capacity     INT                                  NOT NULL,
    daily_cost   INT                                  NOT NULL,
    type         VARCHAR(30)                          NOT NULL,
    CONSTRAINT pk_cars PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(50)                          NOT NULL,
    password VARCHAR(20)                          NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE reservation
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id INT                           NOT NULL,
    car_id    INT                           NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

CREATE TABLE client
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rut          VARCHAR(10)                NOT NULL,
    first_name   VARCHAR(50)                NOT NULL,
    last_name    VARCHAR(50)                NOT NULL,
    email        VARCHAR(50)                NOT NULL,
    phone_number INT                        NOT NULL,
    address      VARCHAR(200)               NOT NULL,
    gift_points  INT                        NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);