CREATE TABLE cars
(
    id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plate_code   VARCHAR(6)                           NOT NULL,
    brand        VARCHAR(30)                          NOT NULL,
    model        VARCHAR(30)                          NOT NULL,
    color        VARCHAR(10)                          NOT NULL,
    factory_year INT                                  NOT NULL,
    capacity     INT                                  NOT NULL,
    daily_cost   INT                                  NOT NULL,
    type         VARCHAR(30)                          NOT NULL,
    CONSTRAINT pk_cars PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(50)                          NOT NULL,
    password VARCHAR(20)                          NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);