spring:
  datasource:
    url: jdbc:h2:mem:rentacar;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
